In [1]:
import pandas as pd

In [2]:
#Step 5
path=r"../dataset/Automobiles_sales_dataset.xlsx"

In [3]:
sales=pd.read_excel(path,sheet_name="sales_dataset")

In [4]:
sales.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-07-05 00:00:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-01-07 00:00:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10 00:00:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [5]:
sales.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [6]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), object(3), str(13)
memory usage: 833.1+ KB

In [7]:
sales.shape

(2823, 25)

In [8]:
print(sales.isnull().sum().sum()/sales.shape[0]*100,"%")

182.6780021253985 %

In [9]:
sales.shape

(2823, 25)

In [10]:
sales.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

In [11]:
for col in sales.columns:
    print(col)

ORDERNUMBER
QUANTITYORDERED
PRICEEACH
ORDERLINENUMBER
SALES
ORDERDATE
STATUS
QTR_ID
MONTH_ID
YEAR_ID
PRODUCTLINE
MSRP
PRODUCTCODE
CUSTOMERNAME
PHONE
ADDRESSLINE1
ADDRESSLINE2
CITY
STATE
POSTALCODE
COUNTRY
TERRITORY
CONTACTLASTNAME
CONTACTFIRSTNAME
DEALSIZE

In [12]:
sales['ADDRESSLINE2'].isnull().sum()

np.int64(2521)

In [13]:
sales.describe

<bound method NDFrame.describe of       ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00
1           10121               34      81.35                5  2765.90
2           10134               41      94.74                2  3884.34
3           10145               45      83.26                6  3746.70
4           10159               49     100.00               14  5205.27
...           ...              ...        ...              ...      ...
2818        10350               20     100.00               15  2244.40
2819        10373               29     100.00                1  3978.51
2820        10386               43     100.00                4  5417.57
2821        10397               34      62.24                1  2116.16
2822        10414               47      65.52                9  3079.44

                ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0          2/24/2003 0:00   Shipped       1         2     2003  ...
1     2003-07-05 00:00:00   Shipped       2         5     2003  ...
2     2003-01-07 00:00:00   Shipped       3         7     2003  ...
3          8/25/2003 0:00   Shipped       3         8     2003  ...
4     2003-10-10 00:00:00   Shipped       4        10     2003  ...
...                   ...       ...     ...       ...      ...  ...
2818  2004-02-12 00:00:00   Shipped       4        12     2004  ...
2819       1/31/2005 0:00   Shipped       1         1     2005  ...
2820  2005-01-03 00:00:00  Resolved       1         3     2005  ...
2821       3/28/2005 0:00   Shipped       1         3     2005  ...
2822  2005-06-05 00:00:00   On Hold       2         5     2005  ...

                       ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0           897 Long Airport Avenue           NaN            NYC    NY
1                59 rue de l'Abbaye           NaN          Reims   NaN
2     27 rue du Colonel Pierre Avia           NaN          Paris   NaN
3                78934 Hillside Dr.           NaN       Pasadena    CA
4                   7734 Strong St.           NaN  San Francisco    CA
...                             ...           ...            ...   ...
2818             C/ Moralzarzal, 86           NaN         Madrid   NaN
2819                    Torikatu 38           NaN           Oulu   NaN
2820             C/ Moralzarzal, 86           NaN         Madrid   NaN
2821          1 rue Alsace-Lorraine           NaN       Toulouse   NaN
2822             8616 Spinnaker Dr.           NaN         Boston    MA

     POSTALCODE  COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0         10022      USA       NaN              Yu             Kwai    Small
1         51100   France      EMEA         Henriot             Paul    Small
2         75508   France      EMEA        Da Cunha           Daniel   Medium
3         90003      USA       NaN           Young            Julie   Medium
4           NaN      USA       NaN           Brown            Julie   Medium
...         ...      ...       ...             ...              ...      ...
2818      28034    Spain      EMEA          Freyre            Diego    Small
2819      90110  Finland      EMEA       Koskitalo           Pirkko   Medium
2820      28034    Spain      EMEA          Freyre            Diego   Medium
2821      31000   France      EMEA          Roulet          Annette    Small
2822      51003      USA       NaN         Yoshido             Juri   Medium

[2823 rows x 25 columns]>

In [14]:
for col in sales.columns:
    if sales[col].isnull().sum()>0:
        print(col,'\t',sales[col].isnull().sum(),'\t',sales[col].dtype)

ADDRESSLINE2 	 2521 	 str
STATE 	 1486 	 str
POSTALCODE 	 76 	 object
TERRITORY 	 1074 	 str

In [15]:
sales['ADDRESSLINE2'].mode()[0]

'Level 3'

In [16]:
sales['ADDRESSLINE2'].value_counts()

ADDRESSLINE2
Level 3        55
Suite 400      48
Level 6        46
Level 15       46
2nd Floor      36
Suite 101      25
Suite 750      20
Floor No. 4    16
Suite 200      10
Name: count, dtype: int64

In [17]:
for col in sales.select_dtypes(include="str").columns:
    print(col,'\t',sales[col].isnull().sum(),'\t Replaced By:',sales[col].mode()[0])
    sales[col]=sales[col].fillna(sales[col].mode()[0])

STATUS 	 0 	 Replaced By: Shipped
PRODUCTLINE 	 0 	 Replaced By: Classic Cars
PRODUCTCODE 	 0 	 Replaced By: S18_3232
CUSTOMERNAME 	 0 	 Replaced By: Euro Shopping Channel
ADDRESSLINE1 	 0 	 Replaced By: C/ Moralzarzal, 86

ADDRESSLINE2 	 2521 	 Replaced By: Level 3
CITY 	 0 	 Replaced By: Madrid
STATE 	 1486 	 Replaced By: CA
COUNTRY 	 0 	 Replaced By: USA
TERRITORY 	 1074 	 Replaced By: EMEA
CONTACTLASTNAME 	 0 	 Replaced By: Freyre
CONTACTFIRSTNAME 	 0 	 Replaced By: Diego
DEALSIZE 	 0 	 Replaced By: Medium

In [18]:
sales.isnull().sum()

ORDERNUMBER          0
QUANTITYORDERED      0
PRICEEACH            0
ORDERLINENUMBER      0
SALES                0
ORDERDATE            0
STATUS               0
QTR_ID               0
MONTH_ID             0
YEAR_ID              0
PRODUCTLINE          0
MSRP                 0
PRODUCTCODE          0
CUSTOMERNAME         0
PHONE                0
ADDRESSLINE1         0
ADDRESSLINE2         0
CITY                 0
STATE                0
POSTALCODE          76
COUNTRY              0
TERRITORY            0
CONTACTLASTNAME      0
CONTACTFIRSTNAME     0
DEALSIZE             0
dtype: int64

In [19]:
sales.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-07-05 00:00:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,Level 3,Reims,CA,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-01-07 00:00:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,Level 3,Paris,CA,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,Level 3,Pasadena,CA,90003,USA,EMEA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10 00:00:00,Shipped,4,10,2003,...,7734 Strong St.,Level 3,San Francisco,CA,NaN,USA,EMEA,Brown,Julie,Medium

In [20]:
sales['ORDERDATE']=pd.to_datetime(sales['ORDERDATE'])

In [21]:
sales.head(20)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-07-05,Shipped,2,5,2003,...,59 rue de l'Abbaye,Level 3,Reims,CA,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-01-07,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,Level 3,Paris,CA,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,Level 3,Pasadena,CA,90003,USA,EMEA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,Level 3,San Francisco,CA,NaN,USA,EMEA,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,2003-10-28,Shipped,4,10,2003,...,9408 Furth Circle,Level 3,Burlingame,CA,94217,USA,EMEA,Hirano,Juri,Medium
6,10180,29,86.13,9,2497.77,2003-11-11,Shipped,4,11,2003,...,"184, chausse de Tournai",Level 3,Lille,CA,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,2003-11-18,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",Level 3,Bergen,CA,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,2003-01-12,Shipped,4,12,2003,...,5557 North Pendale Street,Level 3,San Francisco,CA,NaN,USA,EMEA,Murphy,Julie,Small
9,10211,41,100.00,14,4708.44,2004-01-15,Shipped,1,1,2004,...,"25, rue Lauriston",Level 3,Paris,CA,75016,France,EMEA,Perrier,Dominique,Medium
10,10223,37,100.00,1,3965.66,2004-02-20,Shipped,1,2,2004,...,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium
11,10237,23,100.00,7,2333.12,2004-05-04,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,EMEA,Frick,Michael,Small
12,10251,28,100.00,2,3188.64,2004-05-18,Shipped,2,5,2004,...,7476 Moss Rd.,Level 3,Newark,NJ,94019,USA,EMEA,Brown,William,Medium
13,10263,34,100.00,2,3676.76,2004-06-28,Shipped,2,6,2004,...,25593 South Bay Ln.,Level 3,Bridgewater,CT,97562,USA,EMEA,King,Julie,Medium
14,10275,45,92.83,1,4177.35,2004-07-23,Shipped,3,7,2004,...,"67, rue des Cinquante Otages",Level 3,Nantes,CA,44000,France,EMEA,Labrune,Janine,Medium
15,10285,36,100.00,6,4099.68,2004-08-27,Shipped,3,8,2004,...,39323 Spinnaker Dr.,Level 3,Cambridge,MA,51247,USA,EMEA,Hernandez,Marta,Medium
16,10299,23,100.00,9,2597.39,2004-09-30,Shipped,3,9,2004,...,Keskuskatu 45,Level 3,Helsinki,CA,21240,Finland,EMEA,Karttunen,Matti,Small
17,10309,41,100.00,5,4394.38,2004-10-15,Shipped,4,10,2004,...,Erling Skakkes gate 78,Level 3,Stavern,CA,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
18,10318,46,94.74,1,4358.04,2004-02-11,Shipped,4,11,2004,...,7586 Pompton St.,Level 3,Allentown,PA,70267,USA,EMEA,Yu,Kyung,Medium
19,10329,42,100.00,1,4396.14,2004-11-15,Shipped,4,11,2004,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Medium

In [22]:
sales.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

In [23]:
#Total Sales
print(sales['SALES'].sum())

10032628.85

In [24]:
#TOTAL PROFIT
print((sales['QUANTITYORDERED']*sales['PRICEEACH'])-(sales['QUANTITYORDERED']*sales['MSRP']))

0         21.00
1       -464.10
2        -10.66
3       -528.30
4        245.00
         ...
2818     920.00
2819    1334.00
2820    1978.00
2821     280.16
2822     541.44
Length: 2823, dtype: float64

In [25]:
#Top Selling Products
print(sales.groupby('PRODUCTLINE')['SALES'].sum().sort_values(ascending=False))

PRODUCTLINE
Classic Cars        3919615.66
Vintage Cars        1903150.84
Motorcycles         1166388.34
Trucks and Buses    1127789.84
Planes               975003.57
Ships                714437.13
Trains               226243.47
Name: SALES, dtype: float64

In [26]:
#Region wise sales
print(sales.groupby('COUNTRY')['SALES'].sum())

COUNTRY
Australia       630623.10
Austria         202062.53
Belgium         108412.62
Canada          224078.56
Denmark         245637.15
Finland         329581.91
France         1110916.52
Germany         220472.09
Ireland          57756.43
Italy           374674.31
Japan           188167.81
Norway          307463.70
Philippines      94015.73
Singapore       288488.41
Spain          1215686.92
Sweden          210014.21
Switzerland     117713.56
UK              478880.46
USA            3627982.83
Name: SALES, dtype: float64

In [27]:
#Monthly Sales Analysis
sales['MONTH_ID']=sales['ORDERDATE'].dt.month
print(sales.groupby('MONTH_ID')['SALES'].sum())

MONTH_ID
1      962396.71
2     1005383.81
3      797370.26
4      744538.06
5      862597.77
6      684918.75
7      490103.29
8      723921.76
9      561245.65
10    1272067.31
11    1489274.30
12     438811.18
Name: SALES, dtype: float64

In [28]:
sales.shape

(2823, 25)

In [29]:
#Best 
print(sales.groupby('CUSTOMERNAME')['SALES'].sum().sort_values(ascending=False).head(5))

CUSTOMERNAME
Euro Shopping Channel           912294.11
Mini Gifts Distributors Ltd.    654858.06
Australian Collectors, Co.      200995.41
Muscle Machine Inc              197736.94
La Rochelle Gifts               180124.90
Name: SALES, dtype: float64

In [30]:
sales.info

<bound method DataFrame.info of       ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00
1           10121               34      81.35                5  2765.90
2           10134               41      94.74                2  3884.34
3           10145               45      83.26                6  3746.70
4           10159               49     100.00               14  5205.27
...           ...              ...        ...              ...      ...
2818        10350               20     100.00               15  2244.40
2819        10373               29     100.00                1  3978.51
2820        10386               43     100.00                4  5417.57
2821        10397               34      62.24                1  2116.16
2822        10414               47      65.52                9  3079.44

      ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0    2003-02-24   Shipped       1         2     2003  ...
1    2003-07-05   Shipped       2         7     2003  ...
2    2003-01-07   Shipped       3         1     2003  ...
3    2003-08-25   Shipped       3         8     2003  ...
4    2003-10-10   Shipped       4        10     2003  ...
...         ...       ...     ...       ...      ...  ...
2818 2004-02-12   Shipped       4         2     2004  ...
2819 2005-01-31   Shipped       1         1     2005  ...
2820 2005-01-03  Resolved       1         1     2005  ...
2821 2005-03-28   Shipped       1         3     2005  ...
2822 2005-06-05   On Hold       2         6     2005  ...

                       ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0           897 Long Airport Avenue       Level 3            NYC    NY
1                59 rue de l'Abbaye       Level 3          Reims    CA
2     27 rue du Colonel Pierre Avia       Level 3          Paris    CA
3                78934 Hillside Dr.       Level 3       Pasadena    CA
4                   7734 Strong St.       Level 3  San Francisco    CA
...                             ...           ...            ...   ...
2818             C/ Moralzarzal, 86       Level 3         Madrid    CA
2819                    Torikatu 38       Level 3           Oulu    CA
2820             C/ Moralzarzal, 86       Level 3         Madrid    CA
2821          1 rue Alsace-Lorraine       Level 3       Toulouse    CA
2822             8616 Spinnaker Dr.       Level 3         Boston    MA

     POSTALCODE  COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0         10022      USA      EMEA              Yu             Kwai    Small
1         51100   France      EMEA         Henriot             Paul    Small
2         75508   France      EMEA        Da Cunha           Daniel   Medium
3         90003      USA      EMEA           Young            Julie   Medium
4           NaN      USA      EMEA           Brown            Julie   Medium
...         ...      ...       ...             ...              ...      ...
2818      28034    Spain      EMEA          Freyre            Diego    Small
2819      90110  Finland      EMEA       Koskitalo           Pirkko   Medium
2820      28034    Spain      EMEA          Freyre            Diego   Medium
2821      31000   France      EMEA          Roulet          Annette    Small
2822      51003      USA      EMEA         Yoshido             Juri   Medium

[2823 rows x 25 columns]>

In [31]:
sales=sales.rename(columns={'ORDER_DATE':'ORDERDATE','Country':'COUNTRY'})

In [32]:
filtered_sales=sales.copy()

In [33]:
filtered_sales

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-07-05,Shipped,2,7,2003,...,59 rue de l'Abbaye,Level 3,Reims,CA,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-01-07,Shipped,3,1,2003,...,27 rue du Colonel Pierre Avia,Level 3,Paris,CA,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,Level 3,Pasadena,CA,90003,USA,EMEA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,Level 3,San Francisco,CA,NaN,USA,EMEA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,2004-02-12,Shipped,4,2,2004,...,"C/ Moralzarzal, 86",Level 3,Madrid,CA,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,2005-01-31,Shipped,1,1,2005,...,Torikatu 38,Level 3,Oulu,CA,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,2005-01-03,Resolved,1,1,2005,...,"C/ Moralzarzal, 86",Level 3,Madrid,CA,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,2005-03-28,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,Level 3,Toulouse,CA,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,2005-06-05,On Hold,2,6,2005,...,8616 Spinnaker Dr.,Level 3,Boston,MA,51003,USA,EMEA,Yoshido,Juri,Medium

In [34]:
sales.head(2)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.0,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.9,2003-07-05,Shipped,2,7,2003,...,59 rue de l'Abbaye,Level 3,Reims,CA,51100,France,EMEA,Henriot,Paul,Small

In [35]:
print(sales.columns.tolist())

['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE']

In [36]:
for col in sales.columns:
    print(col[3],col,sales[col].dtype)

E ORDERNUMBER int64
N QUANTITYORDERED int64
C PRICEEACH float64
E ORDERLINENUMBER int64
E SALES float64
E ORDERDATE datetime64[us]
T STATUS str
_ QTR_ID int64
T MONTH_ID int32
R YEAR_ID int64
D PRODUCTLINE str
P MSRP int64
D PRODUCTCODE str
T CUSTOMERNAME str
N PHONE object
R ADDRESSLINE1 str
R ADDRESSLINE2 str
Y CITY str
T STATE str
T POSTALCODE object
N COUNTRY str
R TERRITORY str
T CONTACTLASTNAME str
T CONTACTFIRSTNAME str
L DEALSIZE str

In [37]:
sales.head(2)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.0,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.9,2003-07-05,Shipped,2,7,2003,...,59 rue de l'Abbaye,Level 3,Reims,CA,51100,France,EMEA,Henriot,Paul,Small

In [38]:
sales.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

In [39]:
print(sales.columns.tolist())

['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE']

In [40]:
for col in sales.columns:
    print(repr(col))

'ORDERNUMBER'
'QUANTITYORDERED'
'PRICEEACH'
'ORDERLINENUMBER'
'SALES'
'ORDERDATE'
'STATUS'
'QTR_ID'
'MONTH_ID'
'YEAR_ID'
'PRODUCTLINE'
'MSRP'
'PRODUCTCODE'
'CUSTOMERNAME'
'PHONE'
'ADDRESSLINE1'
'ADDRESSLINE2'
'CITY'
'STATE'
'POSTALCODE'
'COUNTRY'
'TERRITORY'
'CONTACTLASTNAME'
'CONTACTFIRSTNAME'
'DEALSIZE'

In [41]:
filtered_sales.head(2)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.0,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.9,2003-07-05,Shipped,2,7,2003,...,59 rue de l'Abbaye,Level 3,Reims,CA,51100,France,EMEA,Henriot,Paul,Small

In [42]:
((filtered_sales['ORDERNUMBER']).unique())

array([10107, 10121, 10134, 10145, 10159, 10168, 10180, 10188, 10201,
       10211, 10223, 10237, 10251, 10263, 10275, 10285, 10299, 10309,
       10318, 10329, 10341, 10361, 10375, 10388, 10403, 10417, 10103,
       10112, 10126, 10140, 10150, 10163, 10174, 10183, 10194, 10206,
       10215, 10228, 10245, 10258, 10270, 10280, 10291, 10304, 10312,
       10322, 10333, 10347, 10357, 10369, 10381, 10391, 10411, 10424,
       10120, 10210, 10236, 10298, 10308, 10339, 10374, 10402, 10362,
       10105, 10119, 10129, 10143, 10155, 10167, 10178, 10186, 10197,
       10209, 10222, 10248, 10261, 10273, 10283, 10295, 10307, 10316,
       10325, 10337, 10350, 10359, 10373, 10384, 10395, 10400, 10414,
       10114, 10164, 10175, 10207, 10217, 10229, 10259, 10281, 10305,
       10313, 10334, 10370, 10425, 10108, 10122, 10135, 10147, 10169,
       10181, 10191, 10203, 10225, 10238, 10253, 10266, 10276, 10287,
       10300, 10310, 10320, 10363, 10389, 10419, 10117, 10127, 10142,
       10153, 10165, 10176, 10185, 10196, 10208, 10220, 10231, 10247,
       10272, 10282, 10293, 10306, 10314, 10336, 10348, 10371, 10382,
       10413, 10113, 10216, 10189, 10224, 10319, 10104, 10230, 10324,
       10358, 10372, 10160, 10170, 10212, 10376, 10349, 10396, 10377,
       10115, 10141, 10151, 10184, 10195, 10219, 10246, 10271, 10292,
       10412, 10192, 10239, 10277, 10321, 10405, 10109, 10136, 10148,
       10161, 10171, 10204, 10240, 10278, 10301, 10331, 10342, 10356,
       10365, 10390, 10406, 10102, 10111, 10125, 10139, 10149, 10162,
       10173, 10182, 10193, 10205, 10227, 10244, 10256, 10289, 10332,
       10346, 10380, 10422, 10110, 10123, 10137, 10172, 10226, 10241,
       10288, 10311, 10343, 10367, 10378, 10407, 10106, 10131, 10198,
       10250, 10262, 10274, 10284, 10296, 10327, 10338, 10351, 10386,
       10398, 10416, 10100, 10124, 10214, 10302, 10344, 10379, 10420,
       10366, 10303, 10383, 10101, 10243, 10409, 10133, 10235, 10297,
       10353, 10401, 10255, 10421, 10257, 10423, 10269, 10392, 10130,
       10128, 10166, 10177, 10221, 10232, 10394, 10326, 10252, 10265,
       10290, 10323, 10330, 10355, 10146, 10264, 10286, 10249, 10328,
       10415, 10152, 10213, 10315, 10267, 10279, 10158, 10340, 10345,
       10190, 10368, 10335, 10154, 10233, 10385, 10242, 10408, 10317,
       10387, 10364, 10116, 10144, 10156, 10199, 10397, 10352, 10118,
       10294])

In [43]:
filtered_sales.shape[0]

2823

In [44]:
round(float(filtered_sales['SALES'].sum()))

10032629

In [45]:
(filtered_sales.groupby('COUNTRY')['SALES'].sum())

COUNTRY
Australia       630623.10
Austria         202062.53
Belgium         108412.62
Canada          224078.56
Denmark         245637.15
Finland         329581.91
France         1110916.52
Germany         220472.09
Ireland          57756.43
Italy           374674.31
Japan           188167.81
Norway          307463.70
Philippines      94015.73
Singapore       288488.41
Spain          1215686.92
Sweden          210014.21
Switzerland     117713.56
UK              478880.46
USA            3627982.83
Name: SALES, dtype: float64

In [46]:
filtered_sales.groupby('COUNTRY', as_index=False)['SALES'].sum().sort_values('SALES', ascending=False).head(1)

   COUNTRY       SALES
18     USA  3627982.83

In [47]:
(filtered_sales.groupby('COUNTRY', as_index=False)['PRODUCTLINE'].sum().sort_values('PRODUCTLINE', ascending=False).head(1))

   COUNTRY                                        PRODUCTLINE
18     USA  MotorcyclesMotorcyclesMotorcyclesMotorcyclesMo...

In [48]:
filtered_sales['PRODUCTLINE'].max()

'Vintage Cars'

In [49]:
filtered_sales.groupby('MONTH_ID')['SALES'].sum()

MONTH_ID
1      962396.71
2     1005383.81
3      797370.26
4      744538.06
5      862597.77
6      684918.75
7      490103.29
8      723921.76
9      561245.65
10    1272067.31
11    1489274.30
12     438811.18
Name: SALES, dtype: float64

In [50]:
round(float(filtered_sales.groupby('COUNTRY')['SALES'].sum().max()))

3627983

In [51]:
filtered_sales.groupby('COUNTRY')['SALES'].sum().reset_index()

        COUNTRY       SALES
0     Australia   630623.10
1       Austria   202062.53
2       Belgium   108412.62
3        Canada   224078.56
4       Denmark   245637.15
5       Finland   329581.91
6        France  1110916.52
7       Germany   220472.09
8       Ireland    57756.43
9         Italy   374674.31
10        Japan   188167.81
11       Norway   307463.70
12  Philippines    94015.73
13    Singapore   288488.41
14        Spain  1215686.92
15       Sweden   210014.21
16  Switzerland   117713.56
17           UK   478880.46
18          USA  3627982.83

In [52]:
filtered_sales.groupby('MONTH_ID')['SALES'].sum()

MONTH_ID
1      962396.71
2     1005383.81
3      797370.26
4      744538.06
5      862597.77
6      684918.75
7      490103.29
8      723921.76
9      561245.65
10    1272067.31
11    1489274.30
12     438811.18
Name: SALES, dtype: float64

In [54]:
sales.head(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,Level 3,NYC,NY,10022,USA,EMEA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-07-05,Shipped,2,7,2003,...,59 rue de l'Abbaye,Level 3,Reims,CA,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-01-07,Shipped,3,1,2003,...,27 rue du Colonel Pierre Avia,Level 3,Paris,CA,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,Level 3,Pasadena,CA,90003,USA,EMEA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,Level 3,San Francisco,CA,NaN,USA,EMEA,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,2003-10-28,Shipped,4,10,2003,...,9408 Furth Circle,Level 3,Burlingame,CA,94217,USA,EMEA,Hirano,Juri,Medium
6,10180,29,86.13,9,2497.77,2003-11-11,Shipped,4,11,2003,...,"184, chausse de Tournai",Level 3,Lille,CA,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,2003-11-18,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",Level 3,Bergen,CA,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,2003-01-12,Shipped,4,1,2003,...,5557 North Pendale Street,Level 3,San Francisco,CA,NaN,USA,EMEA,Murphy,Julie,Small
9,10211,41,100.00,14,4708.44,2004-01-15,Shipped,1,1,2004,...,"25, rue Lauriston",Level 3,Paris,CA,75016,France,EMEA,Perrier,Dominique,Medium